/Users/paulellson/Library/Application Support/MaxCoin/maxcoin.conf

# Seed nodes
addnode=maxexplorer.cloudapp.net
addnode=maxcoin.cloudapp.net
addnode=maxcoinus.cloudapp.net
addnode=maxcoinasia.cloudapp.net
addnode=213.179.202.19
addnode=91.121.8.25
                addnode=91.121.8.25
addnode=wombat.dar.sh

# Enable RPC
server=1

# RPC information
rpcuser=maxcoinrpc
rpcpassword=haveyouevermetafizzicle

# Mining
gen=1
